<?php
$data = $block->getDeliveryDate();
if ($data) {
?>
    <div class="block block-order-details-view">
        <div class="block-title">
            <strong>Delivery Information</strong>
        </div>
        <div class="block-content">
            <strong class="box-title"><span>Delivery Date</span></strong>
            <div class="box-content">
                <span>Delivery Date: <?= $data['delivery_date'] ?></span><br>
                <span class="delivery-comment-view" style="word-wrap:break-word">Delivery Comment: <?= $data['delivery_comment'] ?></span>
            </div>
        </div>
    </div>
<?php
}
?>
