<?php
/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<strong class="logo">
    <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
         alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
        <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
        <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
    />
</strong>